language: python
python:
- '2.7'
- '3.5'
- '3.6'
#- '3.7-dev'
#- "nightly" # currently points to 3.6-dev
bundler_args: "--retry 3"
install:
- pip install pip --upgrade
- pip install six
- pip install parsimonious
- pip install pytz
- pip install iso8601
- pip install hszinc
- pip install -r requirements.txt
- pip install coveralls
- pip install pytest
- pip install pytest-cov
script:
#- nosetests --with-coverage --cover-package=pyhaystack -v
- python setup.py install
- py.test --cov=pyhaystack tests/
after_success: coveralls
deploy:
  provider: pypi
  user: ChristianTremblay
  password:
    secure: "KwrpIZfE8h+aypiHqPx6U3rKeDmIVow4Oz+g1tjBNDsw+NRKoAIJj2Yh+U+rosrRZdoZ9S2JIhntHO0ffoYHyd/waK7/Z8bUf5nCMj4tN0EArwk0YDbqCwmbFAxQFAVVGBWzPMHvG98RvNepddAQUzQtQ12PlHBgsrt7Y2xnysHNtQDDSH0h61BavRU3QcFJXwiSFRMFT3AFuT9XUu9u/QcATNprKfI23PDY4LTbyFUskbIX3JifchR5PFTy6Ba5HEKOAwhokrCtODcHPdkRX24dQfGZcinW1VOVSJyarkVGFkCFzL9ipVjJIBkYtOA2Eta5s0CJAXDiPFjnLG3NFS3VdJygbjkiX15EF8OLum0MTht4biIJiZHPmu0kqre/tImfbHJ2E7LYhZhBkY/bHsYdZEZg6zLFK4GbiEjm0DzB2JYdx68MsSImQwhgcWvNcb4IVgAV5iiB0miI7Atl828g8vE2xKOZTd3b1+MWXLt0ASRPgreU3hRqM6R2Z9aF7/Ygk7L41YzkqmaGM5jlUHKoD5x9aij8PlRl1MeuRB+EL7E3ne1ju5ZT8Y65ZjD6eRkyS+yK+evl9+JW/Aez5Ab3ousG+ZL2SzjlIuFehcJNVFIetbSe8fhbNA/w8FVkXwYV6mxncJMVZbqlmDYOErSX/m/tToDVKKNmXTr1DXg="
  on:
    branch: master
    python: '3.6'
    distributions: sdist bdist_wheel
    repo: ChristianTremblay/pyhaystack